# Generated by Django 5.0.7 on 2024-08-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspapers", "0003_visitcounter"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="newspaper",
            constraint=models.CheckConstraint(
                check=models.Q("title", "", _negated=True),
                name="non_empty_title",
            ),
        ),
        migrations.AddConstraint(
            model_name="newspaper",
            constraint=models.CheckConstraint(
                check=models.Q("content", "", _negated=True),
                name="non_empty_content",
            ),
        ),
        migrations.AddConstraint(
            model_name="topic",
            constraint=models.CheckConstraint(
                check=models.Q("name", "", _negated=True),
                name="non_empty_name",
            ),
        ),
    ]
